### ISSUE TITLE
The result of cityscapes is strange

### ISSUE THREAD

**Issue by canglangzhige** [DdeGeus/PanopticFCN-IBS#2]
Thanks for your work.
When I train the model with Cityscapes follow [https://github.com/dvlab-research/PanopticFCN/issues/21](https://github.com/dvlab-research/PanopticFCN/issues/url). I get the result like:

![frankfurt_000000_000576_leftImg8bit](https://user-images.githubusercontent.com/48430568/221081485-b6b8306f-f8d1-4d4a-9f1b-b4b672ceb8c4.png)

But the ground truth is：

![frankfurt_000000_000576_gtFine_panoptic](https://user-images.githubusercontent.com/48430568/221081546-4a75856c-8eaa-4b96-bdfa-c11f88bad925.png)

You can see that the segmentation of the front end at the bottom of the image(inside the red rectangular box) is chaotic. 
The same result is found in your paper:

![1](https://user-images.githubusercontent.com/48430568/221081694-dc7baf08-dade-4fd4-ae09-0ca8aad0463f.png)

Why is that?

**Comment by DdeGeus** [comment]
Hi @canglangzhige, my apologies for the late reply. The chaotic/noisy predictions are caused by the fact that the network learns to segment only 19 classes for the Cityscapes dataset, and that the pixels belonging to the _ego-vehicle_, which you indicate with the boxes, are not labeled with one of those 19 classes. As there is no ground-truth label for these regions, they are ignored when the loss is calculated, and the network is never penalized for any predictions in these regions. This results in the noisy predictions.

As far as I know, behavior like this occurs for any network that is trained on the 19 Cityscapes classes. If you want to avoid it, you could make sure that there is a ground-truth label for each pixel.

PS: in the first examples you show, it appears that there are more errors than just the noisy predictions for the _ego-vehicle_. Do you also experience such errors when running our code?
